# Generated by Django 3.2.4 on 2021-07-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_data', models.TextField()),
                ('comment_author', models.CharField(max_length=255)),
                ('comment_source', models.CharField(max_length=255, null=True)),
                ('comment_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
