# Generated by Django 3.2.4 on 2021-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_clean',
            field=models.TextField(null=True),
        ),
    ]
