# Generated by Django 3.2.5 on 2021-07-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_comments_comment_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_OFF',
            field=models.BooleanField(default=False),
        ),
    ]
