# Generated by Django 3.2.5 on 2021-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_comments_comment_degre_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('csv', models.FileField(upload_to='csv/')),
            ],
        ),
    ]
