# Generated by Django 3.2.5 on 2021-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='csv',
            field=models.FileField(upload_to='csv'),
        ),
    ]
